export interface SectionData {
  role: string;
  clauseCode: string;
  order: number;
  questions: string[];
}

export const ISO27001_EN: SectionData[] = [
  // Clause 4 ─── DIRECTION
  {
    role: 'DIRECTION', clauseCode: '4 — Context of the Organization', order: 1,
    questions: [
      'Have you formally identified internal and external issues that may affect the organization\'s ability to achieve its ISMS objectives?',
      'Are these issues documented and periodically reviewed?',
      'Have you identified relevant interested parties for the ISMS (clients, regulators, partners, shareholders)?',
      'Are the requirements (legal, contractual, regulatory) of these interested parties documented and taken into account?',
      'Is the ISMS scope formally defined, documented and approved by management?',
      'Are interfaces and dependencies with entities outside the scope considered in the scope definition?',
      'Is the ISMS established, implemented, maintained and continually improved in accordance with the standard?',
    ],
  },
  {
    role: 'DIRECTION', clauseCode: '5 — Leadership and Commitment', order: 2,
    questions: [
      'Does management demonstrate leadership by assuming responsibility for the effectiveness of the ISMS?',
      'Is the information security policy established, documented, approved and signed by management?',
      'Is the policy consistent with the strategic direction of the organization?',
      'Does the policy include security objectives or provide a framework for setting them?',
      'Does the policy include a commitment to meet applicable requirements?',
      'Does the policy include a commitment to continual improvement of the ISMS?',
      'Is the policy available as documented information and communicated internally?',
      'Is the policy available to external interested parties where appropriate?',
      'Are roles and responsibilities related to information security formally assigned and communicated?',
      'Does management ensure the ISMS achieves its intended outcomes and reports on its performance?',
      'Does management actively promote continual improvement within the organization?',
      'Does management support other management roles to demonstrate leadership in their areas of responsibility?',
    ],
  },
  {
    role: 'DIRECTION', clauseCode: '6 — Planning and Security Objectives', order: 3,
    questions: [
      'Are information security objectives established for relevant functions and levels of the organization?',
      'Are the objectives measurable, consistent with the policy and taking into account risk assessment results?',
      'Are security objectives documented and communicated?',
      'Is there a plan specifying: what will be done, required resources, responsible parties, timelines and how results will be evaluated?',
      'Has management planned actions to address risks and opportunities identified within the ISMS?',
    ],
  },
  {
    role: 'DIRECTION', clauseCode: '9.3 — Management Review', order: 14,
    questions: [
      'Does management conduct ISMS reviews at planned intervals?',
      'Does the review include the status of actions from previous reviews?',
      'Does the review include changes in internal and external issues relevant to the ISMS?',
      'Does the review include feedback on security performance (non-conformities, indicators, monitoring and audit results)?',
      'Does the review include feedback from interested parties?',
      'Does the review include risk assessment results and status of the risk treatment plan?',
      'Does the review include opportunities for continual improvement?',
      'Are the results of the management review documented and maintained as documented information?',
      'Do the review decisions address opportunities for improvement and needs for ISMS changes, including resources?',
    ],
  },
  {
    role: 'DIRECTION', clauseCode: '10 — Continual Improvement', order: 15,
    questions: [
      'Does the organization continually improve the relevance, adequacy and effectiveness of the ISMS?',
      'When a nonconformity occurs, does the organization react to control it and correct its effects?',
      'Are the causes of nonconformities analyzed to prevent recurrence or occurrence elsewhere?',
      'Are corrective actions proportionate to the effects of the nonconformities encountered?',
      'Is the effectiveness of corrective actions evaluated and results documented?',
    ],
  },

  // ─── RSSI (42) ──────────────────────────────────────────────────────────────
  {
    role: 'RSSI', clauseCode: '6.1 — Risk Assessment and Treatment', order: 4,
    questions: [
      'Is an information security risk assessment process defined and documented?',
      'Are risk assessment and acceptance criteria established and maintained?',
      'Does the process ensure that repeated assessments produce consistent, valid and comparable results?',
      'Are risks identified with their owners, along with potential impacts on confidentiality, integrity and availability?',
      'Are risk levels analyzed (likelihood and consequences)?',
      'Are risks evaluated against established criteria to prioritize them for treatment?',
      'Is documented information on the risk assessment process and results retained?',
      'Is a risk treatment process defined and treatment options (modify, retain, avoid, transfer) selected?',
      'Are controls necessary to implement the chosen treatment option determined and compared to Annex A of the standard?',
      'Is a Statement of Applicability (SoA) produced, including retained and excluded controls with justifications?',
      'Is a risk treatment plan formalized and submitted for approval by risk owners?',
      'Have risk owners approved the treatment plan and accepted the residual risk level?',
      'Is documented information on the risk treatment process and results retained?',
      'Is risk assessment renewed at planned intervals and when significant changes are proposed or occur?',
    ],
  },
  {
    role: 'RSSI', clauseCode: '8 — ISMS Operational Implementation', order: 11,
    questions: [
      'Are processes needed to meet ISMS requirements planned, implemented and controlled?',
      'Are criteria for processes defined and processes executed in accordance with these criteria?',
      'Is documented information needed to demonstrate that processes have been carried out as planned retained?',
      'Are outsourced processes relevant to the ISMS identified and controlled?',
      'Is risk assessment carried out at planned intervals or when significant changes are proposed or occur?',
      'Is the risk treatment plan implemented and its implementation status tracked?',
      'Are risk treatment results documented as documented information?',
      'Are planned changes controlled and consequences of unintentional changes reviewed, with corrective actions if necessary?',
    ],
  },
  {
    role: 'RSSI', clauseCode: '9.1 — Monitoring, Measurement, Analysis and Evaluation', order: 12,
    questions: [
      'Does the organization evaluate information security performance and the effectiveness of the ISMS?',
      'Is what needs to be monitored and measured determined (including processes and security controls)?',
      'Are methods for monitoring, measurement, analysis and evaluation defined to produce valid and comparable results?',
      'Is it specified when monitoring and measurement shall be performed?',
      'Is it defined who shall perform monitoring and measurement?',
      'Is it specified when results of monitoring and measurement shall be analyzed and evaluated?',
      'Is it identified who shall analyze and evaluate these results?',
      'Is documented information providing evidence of monitoring and measurement results retained?',
      'Have all Annex A controls been reviewed to determine if they are applicable to the organization?',
      'For excluded controls, is explicit justification provided in the Statement of Applicability?',
      'Are thematic security policies defined, approved by management and communicated to relevant persons?',
      'Is a security incident feedback process in place that feeds into the review of security controls?',
      'Are roles and responsibilities for information security defined, assigned and communicated?',
      'Is an inventory of information assets maintained and does each asset have a designated owner?',
      'Is an information classification scheme defined and applied based on organizational needs?',
      'Are security incident management procedures in place, documented and tested?',
      'Is a technical vulnerability management process implemented and regularly executed?',
      'Are penetration tests or technical audits conducted to verify the effectiveness of security controls?',
      'Is information security continuity planned, implemented and tested?',
      'Are legal, regulatory and contractual requirements relating to information security identified and complied with?',
    ],
  },

  // ─── EMPLOYEE_IT (35) ───────────────────────────────────────────────────────
  {
    role: 'EMPLOYEE_IT', clauseCode: '7.1 — IT Resources and Infrastructure', order: 6,
    questions: [
      'Are the resources needed to establish, implement, maintain and continually improve the ISMS determined and provided?',
      'Is the IT infrastructure (networks, servers, workstations) documented and included in the ISMS scope?',
      'Are resources allocated to security (tools, licenses, personnel) sufficient to achieve ISMS objectives?',
      'Is a complete inventory of technology assets (hardware, software, data) maintained and up to date?',
      'Are access rights managed according to the least privilege principle (registration, modification, revocation)?',
      'Are privileged access accounts (administrators) identified, managed and regularly reviewed?',
      'Are secret authentication credentials subject to specific measures (strong password policy, MFA)?',
      'Are access rights reviewed at regular intervals and upon role changes or departures?',
      'Are malware protection measures in place and kept up to date?',
      'Is a technical vulnerability and patch management process defined and applied within policy-defined timeframes?',
      'Are secure configurations (hardening) of systems defined, documented and applied?',
      'Is sensitive information encrypted in transit and at rest in accordance with an approved encryption policy?',
      'Are regular backups performed, periodically tested and stored in accordance with policy requirements?',
      'Are event logs generated, protected against modification and retained for defined durations?',
      'Are system clocks synchronized to an approved reference time source?',
      'Are network segmentation and filtering measures implemented to isolate sensitive environments?',
      'Is software installation on production systems subject to a formal authorization procedure?',
      'Are development, test and production environments separated and distinct?',
      'Are security tests (code review, penetration tests) performed before deploying new applications to production?',
      'Are connections to external networks subject to documented filtering measures (firewalls, proxies)?',
      'Is a procedure for secure disposal or reuse of media and equipment defined and applied?',
      'Is remote access (VPN, RDP, etc.) authenticated, encrypted and logged?',
      'Are personal data and sensitive data processed in accordance with the classification policy and legal requirements?',
      'Is a security incident management process (detection, reporting, response) formalized and known to the IT team?',
      'Is evidence related to security incidents collected and retained in a manner that preserves its integrity?',
      'Are physical security perimeters defined to protect zones containing critical information and equipment (data center, server room)?',
      'Is physical access to secure areas controlled (badges, biometrics, guards) and logged?',
      'Are equipment protected against environmental threats (fire, flood, power outage)?',
      'Are backup power supplies (UPS, generators) in place and regularly tested?',
      'Are media containing sensitive information securely destroyed when no longer needed?',
      'Are equipment taken off-site subject to appropriate protection measures?',
      'Are IT and electrical cabling protected against interception or physical damage?',
      'Is regular maintenance of equipment performed and documented?',
      'Are special rules in place for working in secure areas (no photography, visitor supervision)?',
      'Is a clean desk / clear screen policy defined and compliance verified?',
    ],
  },

  // ─── EMPLOYEE_HR (22) ───────────────────────────────────────────────────────
  {
    role: 'EMPLOYEE_HR', clauseCode: '7.2 — Competence', order: 7,
    questions: [
      'Are the competencies needed by persons whose work affects information security performance determined?',
      'Are these persons competent on the basis of appropriate education, training or experience?',
      'Are actions taken to acquire necessary competencies (training, recruitment) and their effectiveness evaluated?',
      'Is documented information (training records, degrees, certifications) retained as evidence of competence?',
      'Are information security competencies integrated into job descriptions and personnel evaluations?',
    ],
  },
  {
    role: 'EMPLOYEE_HR', clauseCode: '7.3 — Awareness', order: 8,
    questions: [
      'Are persons working under the organization\'s control aware of the information security policy?',
      'Do staff understand their contribution to ISMS effectiveness and the benefits of improved security performance?',
      'Are staff aware of the implications of not complying with ISMS requirements?',
      'Is a security awareness program in place, planned annually and its content regularly updated?',
      'Is the effectiveness of awareness actions evaluated (simulated phishing tests, quizzes, assessments)?',
    ],
  },
  {
    role: 'EMPLOYEE_HR', clauseCode: '7.4 — Communication and HR Security', order: 9,
    questions: [
      'Are internal and external communication needs relevant to the ISMS determined (what, when, to whom, how)?',
      'Is security-related information communicated to relevant parties in a timely manner?',
      'Are the communication procedures in the event of a security incident known to all employees?',
      'Are background checks performed prior to employment, in accordance with applicable laws and regulations?',
      'Do terms and conditions of employment include the employee\'s and organization\'s responsibilities for information security?',
      'Do all employees and contractors comply with and apply the organization\'s information security policy?',
      'Is a formal disciplinary process defined and communicated for information security violations?',
      'Are information security responsibilities maintained after the end of a contract or role change?',
      'Are access rights revoked and equipment recovered upon employee departure or role change?',
      'Is a confidentiality or non-disclosure agreement signed by each employee and contractor with access to sensitive information?',
      'Are rules and security measures for remote working defined and applied?',
      'Are employees informed and required to report any observed security events or weaknesses?',
    ],
  },

  // ─── AUDITOR (20) ───────────────────────────────────────────────────────────
  {
    role: 'AUDITOR', clauseCode: '7.5 — Documented Information', order: 10,
    questions: [
      'Does the ISMS include the documented information required by the ISO/IEC 27001 standard?',
      'Has the organization determined and included documented information deemed necessary for ISMS effectiveness?',
      'When creating and updating documented information, are aspects of identification, format, media and review/approval ensured?',
      'Is documented information available and usable at the locations and times it is needed?',
      'Is documented information adequately protected (against loss of confidentiality, improper use or loss of integrity)?',
      'Are the distribution, access, retrieval and use of documented information controlled?',
      'Is documented information retained and then disposed of appropriately?',
    ],
  },
  {
    role: 'AUDITOR', clauseCode: '9.2 — Internal ISMS Audit', order: 13,
    questions: [
      'Does the organization conduct internal audits at planned intervals to provide information on ISMS conformity and effectiveness?',
      'Is an audit program defined, implemented and maintained, including frequencies, methods, responsibilities and reporting?',
      'Are auditors selected to ensure objectivity and impartiality of the audit process?',
      'Are audit results reported to relevant management?',
      'Is documented information of the audit program and results retained?',
      'Are corrective actions initiated without undue delay when nonconformities are identified?',
      'Are audit findings used to continually improve the ISMS?',
      'Does the audit program take into account the importance of processes and previous audit results?',
    ],
  },
  {
    role: 'AUDITOR', clauseCode: '10.1 — Nonconformity and Corrective Action', order: 16,
    questions: [
      'When a nonconformity occurs, does the organization react to control it, correct it and deal with the consequences?',
      'Is the cause of the nonconformity determined to prevent recurrence or occurrence elsewhere?',
      'Are corrective actions implemented and their effectiveness reviewed?',
      'Are changes to the ISMS made if necessary following nonconformities?',
      'Is documented information retained as evidence of the nature of nonconformities and actions taken?',
    ],
  },

  // ─── EMPLOYEE_ADMIN (26) ────────────────────────────────────────────────────
  {
    role: 'EMPLOYEE_ADMIN', clauseCode: 'General — Administrative Security', order: 17,
    questions: [
      'Are business process risk ownership responsibilities clearly defined and assigned to appropriate stakeholders?',
    ],
  },
  {
    role: 'EMPLOYEE_ADMIN', clauseCode: '6.1 — Business Process Risk Ownership', order: 5,
    questions: [
      'Are information assets supporting business processes identified and classified?',
      'Are business process owners assigned responsibility for associated information security risks?',
      'Are access rights to information systems supporting business processes reviewed regularly?',
      'Are third-party and supplier access rights to organizational systems controlled and monitored?',
      'Are contracts with suppliers reviewed to ensure information security requirements are included?',
      'Are changes to systems supporting business operations managed through a formal change control process?',
      'Are business continuity plans in place and tested to ensure continuity of critical business processes?',
      'Are information security requirements included in project management processes?',
      'Are information security risk assessments performed as part of business change management?',
      'Are data retention and disposal procedures defined for business process data?',
      'Are privacy and personal data protection requirements addressed in business process design?',
      'Are legal and regulatory requirements applicable to business processes identified and complied with?',
      'Are employee security responsibilities in business processes documented in job descriptions?',
      'Are security incidents affecting business processes reported and managed according to defined procedures?',
      'Are business process performance metrics including security indicators monitored and reported?',
      'Are business process documentation and procedures kept up to date and accessible?',
      'Are approval workflows for business-critical information changes documented and enforced?',
      'Are separation of duties controls applied to prevent conflicts of interest in sensitive business processes?',
      'Are audit trails maintained for key business process transactions?',
      'Are backup and recovery procedures for business-critical data tested regularly?',
      'Are physical security controls adequate for locations where business processes are conducted?',
      'Are mobile device and remote working policies applied to employees conducting business processes?',
      'Are training programs in place to ensure employees are competent in secure business process execution?',
      'Are results of business process security assessments reviewed by management and acted upon?',
      'Are information security requirements considered when outsourcing business processes?',
    ],
  },
];
